spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/carrotmarket;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa :
    hibernate :
      ddl-auto : create
    properties :
      hibernate :
#        print out
#        show_sql : true
        format_sql : true
        default_batch_fetch_size : 100  #in query의 개수를 몇 개로 할건가?!
    # 트랜잭션을 종료할 때 영속성 컨텍스트를 닫고, 디비 커넥션도 반환한다.
    # 커넥션 리소스를 낭비하지 않는다..
    # Service, repository에서만 지연로딩을 쓸 수 있음
    open-in-view : false #기본값

logging :
  level :
#    logger
    org.hibernate.SQL : debug
#    org.hibernate.type : trace






